import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/component/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "THtech crud-application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <div className="">
      <Navbar/>  
    <div className="mt-8">{children}</div>
     </div>
        </body>
    </html>
  );
}
